name: ai-for-stock-exchange-infra

services:
  terraform:
    build:
      context: .
      dockerfile: dockerfile.terraform
    image: ai-for-stock-exchange-infra:dev
    container_name: ai-for-stock-exchange-infra
    env_file:
      - .env
    restart: unless-stopped
    command: ["tail", "-f", "/dev/null"]
